using AdminAssistant.Modules.AccountsModule.DashboardWidgetsUI;
using AdminAssistant.Web.Modules.AccountsModule.DashboardWidgets;

namespace Microsoft.Extensions.DependencyInjection;

public static partial class DependencyInjectionExtensions
{
    public static IServiceCollection AddAdminAssistantDynamicWebComponents(this IServiceCollection services)
    {
        // Add Accounts Components ...
        services.AddKeyedTransient<Type>(AccountsSummaryDashboardWidgetViewModel.AccountsSummaryDashboardWidgetKey, (provider, o) => typeof(AccountsSummaryDashboardWidget));

        // Add Admin Components ...

        // Add Asset Register Components ...

        // Add Billing Components ...

        // Add Budget Components ...

        // Add Calendar Components ...

        // Add Contacts Components ...

        // Add Core Components ...

        // Add Dashboard Components ...

        // Add Documents Components ...

        // Add Mail Components ...

        // Add Reports Components ...

        // Add Notes Components ...

        // Add Tasks Components ...

        // Add Shared Components ...

        return services;
    }
}
