name: $(BuildID)

trigger: # CI Builds
  batch: true
  branches:
    include:
    - dev
    - master
  paths:
    exclude:
    - ./DevOps
    - ./docs

pr: none # Disable PR builds

resources:
- repo: self
  clean: true

stages:
- stage: PRBuild
  jobs:
  - job: PRBuild
    pool: # https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops
      vmImage: 'windows-latest' # Need windows to get code coverage report - https://github.com/actions/virtual-environments/tree/master/images/win
      #name: Self-Hosted
    steps:
    # Set-up build environment ...
    - task: UseDotNet@2
      displayName: 'Ensure CI uses correct sdk Version'
      inputs:
        packageType: 'sdk'
        version: '7.0.x'
        includePreviewVersions: false
    # Restore dependencies ...
    - task: DotNetCoreCLI@2
      displayName: 'dotnet restore'
      inputs:
        command: 'restore'
        projects: 'src/AdminAssistant.sln'
        feedsToUse: 'config'
        nugetConfigPath: 'DevOps/NuGet.config'
    # Sonar Cloud Prepare
    - task: SonarCloudPrepare@1
      inputs:
        SonarCloud: 'SonarCube'
        organization: 'simongeering'
        scannerMode: 'MSBuild'
        projectKey: 'SimonGeering_AdminAssistant'
        projectName: 'AdminAssistant'
    # Build ...
    - task: DotNetCoreCLI@2
      displayName: 'dotnet build'
      inputs:
        command: 'build'
        projects: 'src/AdminAssistant.sln' # For now this will do to exclude Xamarin projects. May later need an AdminAssistant.NonXamarin.sln
        arguments: '--configuration Release --no-restore'
    # Run Unit Tests ...
    - task: DotNetCoreCLI@2
      displayName: 'dotnet test'
      inputs:
        command: 'test'
        projects: 'src/AdminAssistant.sln'
        testRunTitle: 'Unit Tests'
        arguments: '--configuration Release --no-build --collect "Code coverage"'
        #arguments: '--configuration Release --filter "Category=Unit" --no-build'
    # Sonar Cloud Analyze and Publish
    - task: SonarCloudAnalyze@1
    - task: SonarCloudPublish@1
      inputs:
        pollingTimeoutSec: '300'
