name: $(BuildID)

trigger: # CI Builds
  batch: true
  branches:
    include:
    - dev
    - main
  paths:
    exclude:
    - ./DevOps
    - ./docs

pr: none # Disable PR builds

resources:
- repo: self
  clean: true

stages:
- stage: PRBuild
  jobs:
  - job: PRBuild
    pool: # https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops
      vmImage: 'windows-latest' # Need windows to get code coverage report - https://github.com/actions/virtual-environments/tree/master/images/win
      #name: Self-Hosted
    steps:
    # Set-up build environment ...
    - task: UseDotNet@2
      displayName: 'Ensure CI uses correct sdk Version'
      inputs:
        packageType: 'sdk'
        version: '9.0.x'
        includePreviewVersions: false
    # Restore dependencies ...
    - task: DotNetCoreCLI@2
      displayName: 'dotnet restore'
      inputs:
        command: 'restore'
        projects: 'src/AdminAssistant.slnx'
        feedsToUse: 'config'
        nugetConfigPath: 'DevOps/NuGet.config'
    # Sonar Cloud Prepare ...
#    - task: SonarCloudPrepare@1
#      inputs:
#        SonarCloud: 'SonarCube'
#        organization: 'simongeering'
#        scannerMode: 'MSBuild'
#        projectKey: 'SimonGeering_AdminAssistant'
#        projectName: 'AdminAssistant'
    # Build ...
    - task: DotNetCoreCLI@2
      displayName: 'dotnet build'
      inputs:
        command: 'build'
        projects: 'src/AdminAssistant.slnx'
        arguments: '--configuration Release --no-restore'
    # Run Unit Tests ...
    - task: DotNetCoreCLI@2
      displayName: 'dotnet test'
      inputs:
        command: 'test'
        projects: 'src/AdminAssistant.slnx'
        arguments: '--configuration Release --no-build --collect "Code coverage" --settings "$(Build.SourcesDirectory)\src\AdminAssistant.Test\.runsettings" --filter "Category=Unit"'
        publishTestResults: true
        testRunTitle: 'Unit Tests'
    # Sonar Cloud Analyze and Publish ...
#    - task: SonarCloudAnalyze@1
#    - task: SonarCloudPublish@1
#      inputs:
#        pollingTimeoutSec: '300'
