global using AdminAssistant.Infrastructure.Providers;
global using AdminAssistant.Primitives.UI;
global using AdminAssistant.UI.Shared.WebAPIClient.v1;
global using CommunityToolkit.Mvvm.Input;
global using CommunityToolkit.Mvvm.Messaging;
global using CommunityToolkit.Mvvm.Messaging.Messages;
global using FluentValidation.Results;
global using SimonGeering.Framework.Primitives;
global using System.ComponentModel;
