# https://prometheus.io/docs/introduction/overview/
scrape_configs:
  - job_name: 'otel-collector'
    scrape_interval: 3s
    static_configs:
      - targets: ['otel:8889']
      - targets: ['otel:8888']
