// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

namespace AdminAssistant.DAL.EntityFramework.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200217212153_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AdminAssistant.Accounts.DAL.EntityFramework.Model.AddressEntity", b =>
                {
                    b.Property<int>("AddressID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuditID")
                        .HasColumnType("int");

                    b.HasKey("AddressID");

                    b.HasIndex("AuditID")
                        .IsUnique();

                    b.ToTable("Address");
                });

            modelBuilder.Entity("AdminAssistant.Accounts.DAL.EntityFramework.Model.AssetEntity", b =>
                {
                    b.Property<int>("AssetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuditID")
                        .HasColumnType("int");

                    b.Property<int>("DepreciatedValue")
                        .HasColumnType("int");

                    b.Property<int>("OwnerID")
                        .HasColumnType("int");

                    b.Property<int>("PurchasePrice")
                        .HasColumnType("int");

                    b.Property<int>("ReplacementCost")
                        .HasColumnType("int");

                    b.HasKey("AssetID");

                    b.HasIndex("AuditID")
                        .IsUnique();

                    b.ToTable("Asset");
                });

            modelBuilder.Entity("AdminAssistant.Accounts.DAL.EntityFramework.Model.AuditEntity", b =>
                {
                    b.Property<int>("AuditID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ArchivedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasDefaultValue(null);

                    b.Property<DateTime>("ArchivedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(true);

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("DeletedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasDefaultValue(null);

                    b.Property<DateTime>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasDefaultValue(null);

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("AuditID");

                    b.ToTable("Audit");
                });

            modelBuilder.Entity("AdminAssistant.Accounts.DAL.EntityFramework.Model.BankAccountEntity", b =>
                {
                    b.Property<int>("BankAccountID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(true);

                    b.Property<int>("AuditID")
                        .HasColumnType("int");

                    b.Property<int>("BankAccountTypeID")
                        .HasColumnType("int");

                    b.Property<int>("CurrencyID")
                        .HasColumnType("int");

                    b.Property<int>("CurrentBalance")
                        .HasColumnType("int");

                    b.Property<bool>("IsBudgeted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("OpenedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("OpeningBalance")
                        .HasColumnType("int");

                    b.Property<int>("OwnerID")
                        .HasColumnType("int");

                    b.HasKey("BankAccountID");

                    b.HasIndex("AuditID")
                        .IsUnique();

                    b.HasIndex("CurrencyID");

                    b.HasIndex("OwnerID");

                    b.ToTable("BankAccount");
                });

            modelBuilder.Entity("AdminAssistant.Accounts.DAL.EntityFramework.Model.BankAccountTransactionEntity", b =>
                {
                    b.Property<int>("BankAccountTransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuditID")
                        .HasColumnType("int");

                    b.Property<int>("BankAccountID")
                        .HasColumnType("int");

                    b.Property<int>("Credit")
                        .HasColumnType("int");

                    b.Property<int>("CurrencyID")
                        .HasColumnType("int");

                    b.Property<int>("Debit")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255)
                        .IsUnicode(true);

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(4000)")
                        .HasMaxLength(4000)
                        .IsUnicode(true);

                    b.Property<int>("PayeeID")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("BankAccountTransactionID");

                    b.HasIndex("AuditID");

                    b.ToTable("BankAccountTransaction");
                });

            modelBuilder.Entity("AdminAssistant.Accounts.DAL.EntityFramework.Model.BankAccountTypeEntity", b =>
                {
                    b.Property<int>("BankAccountTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AllowCompany")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("AllowPersonal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255)
                        .IsUnicode(true);

                    b.Property<bool>("IsDeprecated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("BankAccountTypeID");

                    b.ToTable("BankAccountType");

                    b.HasData(
                        new
                        {
                            BankAccountTypeID = 1,
                            AllowCompany = true,
                            AllowPersonal = true,
                            Description = "Current Account",
                            IsDeprecated = false
                        },
                        new
                        {
                            BankAccountTypeID = 2,
                            AllowCompany = true,
                            AllowPersonal = true,
                            Description = "Savings Account",
                            IsDeprecated = false
                        });
                });

            modelBuilder.Entity("AdminAssistant.Accounts.DAL.EntityFramework.Model.BudgetEntity", b =>
                {
                    b.Property<int>("BudgetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuditID")
                        .HasColumnType("int");

                    b.Property<string>("BudgetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(true);

                    b.Property<int>("OwnerID")
                        .HasColumnType("int");

                    b.HasKey("BudgetID");

                    b.HasIndex("AuditID");

                    b.ToTable("Budget");
                });

            modelBuilder.Entity("AdminAssistant.Accounts.DAL.EntityFramework.Model.BudgetEntryEntity", b =>
                {
                    b.Property<int>("BudgetEntryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuditID")
                        .HasColumnType("int");

                    b.Property<int>("BudgetID")
                        .HasColumnType("int");

                    b.HasKey("BudgetEntryID");

                    b.HasIndex("AuditID");

                    b.ToTable("BudgetEntry");
                });

            modelBuilder.Entity("AdminAssistant.Accounts.DAL.EntityFramework.Model.CompanyEntity", b =>
                {
                    b.Property<int>("CompanyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuditID")
                        .HasColumnType("int");

                    b.Property<string>("CompanyNumber")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasDefaultValue(null);

                    b.Property<DateTime>("DateOfIncorporation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(true);

                    b.Property<int>("UserProfileID")
                        .HasColumnType("int");

                    b.Property<string>("VATNumber")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasDefaultValue(null);

                    b.HasKey("CompanyID");

                    b.HasIndex("AuditID")
                        .IsUnique();

                    b.HasIndex("UserProfileID");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("AdminAssistant.Accounts.DAL.EntityFramework.Model.ContactAddressEntity", b =>
                {
                    b.Property<int>("ContactAddressID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AddressID")
                        .HasColumnType("int");

                    b.Property<int>("ContactID")
                        .HasColumnType("int");

                    b.HasKey("ContactAddressID");

                    b.ToTable("ContactAddress");
                });

            modelBuilder.Entity("AdminAssistant.Accounts.DAL.EntityFramework.Model.ContactEntity", b =>
                {
                    b.Property<int>("ContactID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuditID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("OwnerID")
                        .HasColumnType("int");

                    b.Property<int>("TitleID")
                        .HasColumnType("int");

                    b.HasKey("ContactID");

                    b.HasIndex("AuditID");

                    b.ToTable("Contact");
                });

            modelBuilder.Entity("AdminAssistant.Accounts.DAL.EntityFramework.Model.CurrencyEntity", b =>
                {
                    b.Property<int>("CurrencyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DecimalFormat")
                        .IsRequired()
                        .HasColumnType("CHAR(5)")
                        .HasMaxLength(5);

                    b.Property<bool>("IsDeprecated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("CHAR(3)")
                        .HasMaxLength(3)
                        .IsUnicode(true);

                    b.HasKey("CurrencyID");

                    b.ToTable("Currency");

                    b.HasData(
                        new
                        {
                            CurrencyID = 1,
                            DecimalFormat = "2.2-2",
                            IsDeprecated = false,
                            Symbol = "GBP"
                        },
                        new
                        {
                            CurrencyID = 2,
                            DecimalFormat = "2.2-2",
                            IsDeprecated = false,
                            Symbol = "EUR"
                        },
                        new
                        {
                            CurrencyID = 3,
                            DecimalFormat = "2.2-2",
                            IsDeprecated = false,
                            Symbol = "USD"
                        });
                });

            modelBuilder.Entity("AdminAssistant.Accounts.DAL.EntityFramework.Model.DocumentEntity", b =>
                {
                    b.Property<int>("DocumentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuditID")
                        .HasColumnType("int");

                    b.Property<int>("OwnerID")
                        .HasColumnType("int");

                    b.HasKey("DocumentID");

                    b.HasIndex("AuditID");

                    b.ToTable("Document");
                });

            modelBuilder.Entity("AdminAssistant.Accounts.DAL.EntityFramework.Model.OwnerEntity", b =>
                {
                    b.Property<int>("OwnerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CompanyID")
                        .HasColumnType("int");

                    b.Property<int?>("PersonalDetailsID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("OwnerID");

                    b.HasIndex("PersonalDetailsID");

                    b.HasIndex("CompanyID", "PersonalDetailsID")
                        .IsUnique()
                        .HasFilter("[CompanyID] IS NOT NULL AND [PersonalDetailsID] IS NOT NULL");

                    b.ToTable("Owner");
                });

            modelBuilder.Entity("AdminAssistant.Accounts.DAL.EntityFramework.Model.PayeeEntity", b =>
                {
                    b.Property<int>("PayeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuditID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(true);

                    b.HasKey("PayeeID");

                    b.HasIndex("AuditID");

                    b.ToTable("Payee");
                });

            modelBuilder.Entity("AdminAssistant.Accounts.DAL.EntityFramework.Model.PermissionEntity", b =>
                {
                    b.Property<int>("PermissionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PermissionKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(true);

                    b.HasKey("PermissionID");

                    b.HasIndex("PermissionKey")
                        .IsUnique();

                    b.ToTable("Permission");
                });

            modelBuilder.Entity("AdminAssistant.Accounts.DAL.EntityFramework.Model.PersonalDetailsEntity", b =>
                {
                    b.Property<int>("PersonalDetailsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuditID")
                        .HasColumnType("int");

                    b.Property<int>("UserProfileID")
                        .HasColumnType("int");

                    b.HasKey("PersonalDetailsID");

                    b.HasIndex("AuditID")
                        .IsUnique();

                    b.HasIndex("UserProfileID")
                        .IsUnique();

                    b.ToTable("PersonalDetails");
                });

            modelBuilder.Entity("AdminAssistant.Accounts.DAL.EntityFramework.Model.SettingEntity", b =>
                {
                    b.Property<int>("SettingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SettingKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(true);

                    b.HasKey("SettingID");

                    b.HasIndex("SettingKey")
                        .IsUnique();

                    b.ToTable("Setting");
                });

            modelBuilder.Entity("AdminAssistant.Accounts.DAL.EntityFramework.Model.UserProfileEntity", b =>
                {
                    b.Property<int>("UserProfileID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuditID")
                        .HasColumnType("int");

                    b.Property<string>("MSGraphID")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasDefaultValue(null);

                    b.Property<string>("SignOn")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(true);

                    b.HasKey("UserProfileID");

                    b.HasIndex("AuditID")
                        .IsUnique();

                    b.HasIndex("SignOn")
                        .IsUnique();

                    b.ToTable("UserProfile");
                });

            modelBuilder.Entity("AdminAssistant.Accounts.DAL.EntityFramework.Model.UserProfilePermissionEntity", b =>
                {
                    b.Property<int>("UserProfilePermissionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PermissionID")
                        .HasColumnType("int");

                    b.Property<int>("UserProfileID")
                        .HasColumnType("int");

                    b.HasKey("UserProfilePermissionID");

                    b.HasIndex("PermissionID");

                    b.HasIndex("UserProfileID", "PermissionID")
                        .IsUnique();

                    b.ToTable("UserProfilePermission");
                });

            modelBuilder.Entity("AdminAssistant.Accounts.DAL.EntityFramework.Model.UserProfileSettingEntity", b =>
                {
                    b.Property<int>("UserProfileSettingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("SettingID")
                        .HasColumnType("int");

                    b.Property<int>("UserProfileID")
                        .HasColumnType("int");

                    b.HasKey("UserProfileSettingID");

                    b.HasIndex("SettingID");

                    b.HasIndex("UserProfileID", "SettingID")
                        .IsUnique();

                    b.ToTable("UserProfileSetting");
                });

            modelBuilder.Entity("AdminAssistant.Accounts.DAL.EntityFramework.Model.AddressEntity", b =>
                {
                    b.HasOne("AdminAssistant.Accounts.DAL.EntityFramework.Model.AuditEntity", "Audit")
                        .WithOne("Address")
                        .HasForeignKey("AdminAssistant.Accounts.DAL.EntityFramework.Model.AddressEntity", "AuditID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AdminAssistant.Accounts.DAL.EntityFramework.Model.AssetEntity", b =>
                {
                    b.HasOne("AdminAssistant.Accounts.DAL.EntityFramework.Model.AuditEntity", "Audit")
                        .WithOne("Asset")
                        .HasForeignKey("AdminAssistant.Accounts.DAL.EntityFramework.Model.AssetEntity", "AuditID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AdminAssistant.Accounts.DAL.EntityFramework.Model.BankAccountEntity", b =>
                {
                    b.HasOne("AdminAssistant.Accounts.DAL.EntityFramework.Model.AuditEntity", "Audit")
                        .WithOne("BankAccount")
                        .HasForeignKey("AdminAssistant.Accounts.DAL.EntityFramework.Model.BankAccountEntity", "AuditID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AdminAssistant.Accounts.DAL.EntityFramework.Model.CurrencyEntity", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AdminAssistant.Accounts.DAL.EntityFramework.Model.OwnerEntity", "Owner")
                        .WithMany("BankAccounts")
                        .HasForeignKey("OwnerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AdminAssistant.Accounts.DAL.EntityFramework.Model.BankAccountTransactionEntity", b =>
                {
                    b.HasOne("AdminAssistant.Accounts.DAL.EntityFramework.Model.AuditEntity", "Audit")
                        .WithMany()
                        .HasForeignKey("AuditID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AdminAssistant.Accounts.DAL.EntityFramework.Model.BudgetEntity", b =>
                {
                    b.HasOne("AdminAssistant.Accounts.DAL.EntityFramework.Model.AuditEntity", "Audit")
                        .WithMany()
                        .HasForeignKey("AuditID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AdminAssistant.Accounts.DAL.EntityFramework.Model.BudgetEntryEntity", b =>
                {
                    b.HasOne("AdminAssistant.Accounts.DAL.EntityFramework.Model.AuditEntity", "Audit")
                        .WithMany()
                        .HasForeignKey("AuditID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AdminAssistant.Accounts.DAL.EntityFramework.Model.CompanyEntity", b =>
                {
                    b.HasOne("AdminAssistant.Accounts.DAL.EntityFramework.Model.AuditEntity", "Audit")
                        .WithOne("Company")
                        .HasForeignKey("AdminAssistant.Accounts.DAL.EntityFramework.Model.CompanyEntity", "AuditID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AdminAssistant.Accounts.DAL.EntityFramework.Model.UserProfileEntity", "UserProfile")
                        .WithMany("Companies")
                        .HasForeignKey("UserProfileID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AdminAssistant.Accounts.DAL.EntityFramework.Model.ContactEntity", b =>
                {
                    b.HasOne("AdminAssistant.Accounts.DAL.EntityFramework.Model.AuditEntity", "Audit")
                        .WithMany()
                        .HasForeignKey("AuditID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AdminAssistant.Accounts.DAL.EntityFramework.Model.DocumentEntity", b =>
                {
                    b.HasOne("AdminAssistant.Accounts.DAL.EntityFramework.Model.AuditEntity", "Audit")
                        .WithMany()
                        .HasForeignKey("AuditID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AdminAssistant.Accounts.DAL.EntityFramework.Model.OwnerEntity", b =>
                {
                    b.HasOne("AdminAssistant.Accounts.DAL.EntityFramework.Model.CompanyEntity", "Company")
                        .WithMany("Owns")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AdminAssistant.Accounts.DAL.EntityFramework.Model.PersonalDetailsEntity", "PersonalDetails")
                        .WithMany("Owns")
                        .HasForeignKey("PersonalDetailsID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AdminAssistant.Accounts.DAL.EntityFramework.Model.PayeeEntity", b =>
                {
                    b.HasOne("AdminAssistant.Accounts.DAL.EntityFramework.Model.AuditEntity", "Audit")
                        .WithMany()
                        .HasForeignKey("AuditID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AdminAssistant.Accounts.DAL.EntityFramework.Model.PersonalDetailsEntity", b =>
                {
                    b.HasOne("AdminAssistant.Accounts.DAL.EntityFramework.Model.AuditEntity", "Audit")
                        .WithOne("PersonalDetails")
                        .HasForeignKey("AdminAssistant.Accounts.DAL.EntityFramework.Model.PersonalDetailsEntity", "AuditID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AdminAssistant.Accounts.DAL.EntityFramework.Model.UserProfileEntity", "UserProfile")
                        .WithOne("PersonalDetails")
                        .HasForeignKey("AdminAssistant.Accounts.DAL.EntityFramework.Model.PersonalDetailsEntity", "UserProfileID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AdminAssistant.Accounts.DAL.EntityFramework.Model.UserProfileEntity", b =>
                {
                    b.HasOne("AdminAssistant.Accounts.DAL.EntityFramework.Model.AuditEntity", "Audit")
                        .WithOne("UserProfile")
                        .HasForeignKey("AdminAssistant.Accounts.DAL.EntityFramework.Model.UserProfileEntity", "AuditID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AdminAssistant.Accounts.DAL.EntityFramework.Model.UserProfilePermissionEntity", b =>
                {
                    b.HasOne("AdminAssistant.Accounts.DAL.EntityFramework.Model.PermissionEntity", "Permission")
                        .WithMany("UserProfilePermissions")
                        .HasForeignKey("PermissionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AdminAssistant.Accounts.DAL.EntityFramework.Model.UserProfileEntity", "UserProfile")
                        .WithMany("Permissions")
                        .HasForeignKey("UserProfileID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AdminAssistant.Accounts.DAL.EntityFramework.Model.UserProfileSettingEntity", b =>
                {
                    b.HasOne("AdminAssistant.Accounts.DAL.EntityFramework.Model.SettingEntity", "Setting")
                        .WithMany("UserProfileSettings")
                        .HasForeignKey("SettingID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AdminAssistant.Accounts.DAL.EntityFramework.Model.UserProfileEntity", "UserProfile")
                        .WithMany("Settings")
                        .HasForeignKey("UserProfileID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
