version: '3.7'
#
# Docker Reference Docs
# https://docs.docker.com/compose/compose-file/build/
#
services:
  adminassistant.sqlserver:
    # https://learn.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker?view=sql-server-ver16&preserve-view=true&pivots=cs1-powershell
    container_name: adminassistant_sqlserver
    image:  mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "127.0.0.1:1433:1433"
    env_file:
      - dev.env

  adminassistant.blazor.server:
    container_name: adminassistant_blazorserver
    image: ${DOCKER_REGISTRY-}adminassistant/blazorserver
    build:
      context: .
      dockerfile: AdminAssistant.Blazor.Server/Dockerfile
    depends_on:
      - adminassistant.sqlserver
