version: '3.7'
#
# Docker Reference Docs
# https://docs.docker.com/compose/compose-file/build/
#
services:
  adminassistant.sqlserver:
    container_name: adminassistant_sqlserver
    image:  mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    env_file:
      - development.env
  adminassistant.blazor.server:
    container_name: adminassistant_blazorserver
    image: ${DOCKER_REGISTRY-}adminassistant/blazorserver
    build:
      context: .
      dockerfile: AdminAssistant.Blazor.Server/Dockerfile
    depends_on:
      - adminassistant.sqlserver
